# Generated by Django 5.2.8 on 2025-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='video_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
