# Generated by Django 5.2.8 on 2025-12-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_confidence',
            field=models.FloatField(default=0.0, help_text='AI detection confidence (0-100)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='analysis_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='video_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified - Authentic'), ('duplicate', 'Duplicate Video'), ('ai_generated', 'AI-Generated Detected'), ('suspicious', 'Suspicious - Manual Review')], default='pending', max_length=20),
        ),
    ]
